### ISSUE TITLE
Incompatible with Reaction Commerce v0.15.1^

### ISSUE THREAD

**Issue by HadenHiles** [ramusus/reaction-flat-pages#9]
In Reaction Commerce (RC) v0.15.1 on the **development** branch this package is no longer compatible because RC started using ES6 imports to manage dependancies and a `package.js` is no longer required.

After adding this package and running `reaction` using the new [reaction-cli](https://www.npmjs.com/package/reaction-cli) I get an error regarding the job-collection package. See [this issue](https://github.com/vsivsi/meteor-job-collection/issues/58#issuecomment-72272402) for more detail on the error.

I'm confident that a conversion of the package to use the ES6 imports will resolve this issue, given that `reaction-flat-pages` doesn't override `Mongo.Collection` directly (I didn't see this done anywhere) and the error is most likely related to it's underlying dependancies in the `package.js`.

If I do end up converting this package to be compatible with the new RC before it is done by someone else I will be sure to create a [PR](https://github.com/ramusus/reaction-flat-pages/pulls).

**Comment by josx** [comment]
This feature is still missing in reaction.
Make it compatible with the newest version, is it a big tasks to do?

**Comment by ramusus** [comment]
@josx Unfortunately, I don't have a time to work on this project right now. But you can feel free to make it compatible and open a PR.
